# Standards: 0.11
---

# 4.1.6 Ensure events that modify the system's network environment are collected(Scored)

- name: 4.1.6 Ensure events that modify the system's network environment are collected(Scored)(Verify registered output matches)
  lineinfile:
    path: "{{ cis_audit_rules_filename }}"
    line: "{{ item }}"
  with_items:
    - '# 4.1.6 Ensure events that modify date and time information are collected'
    - '-a always,exit -F arch=b64 -S sethostname -S setdomainname -k system-locale'
    - '-a always,exit -F arch=b32 -S sethostname -S setdomainname -k system-locale'
    - '-w /etc/issue -p wa -k system-locale'
    - '-w /etc/issue.net -p wa -k system-locale'
    - '-w /etc/hosts -p wa -k system-locale'
    - '-w /etc/sysconfig/network -p wa -k system-locale'
    - '-w /etc/sysconfig/network-scripts/ -p wa -k system-locale'
  tags:
    - "4.1.6"
    - level-2
    - section-4
    - scored
