# Standards: 0.11
---

# 4.1.2 Ensure auditd service is enabled (Scored)    
- name: 4.1.2 Ensure /sbin/audispd has correct permissions (Scored)
  file:
    path: /sbin/audispd
    owner: root
    group: root
    mode: '0755'
  tags:
    - level-2
    - section-4
    - "4.1.2"
    - scored

- name: 4.1.2 Ensure auditd service is started (Scored)
  service:
    name: auditd
    enabled: yes
    state: started
  tags:
    - level-2
    - section-4
    - "4.1.2"
    - scored
