# Standards: 0.11
---

# 4.1.16 Ensure system administrator actions (sudolog) are collected (Scored)

- name: 4.1.16 Ensure system administrator actions (sudolog) are collected(Verify registered output matches)
  lineinfile:
    path: "{{ cis_audit_rules_filename }}"
    line: "{{ item }}"
  with_items:
    - '# 4.1.16 Ensure system administrator actions (sudolog) are collected'
    - '-w /var/log/sudo.log -p wa -k actions'
  tags:
    - "4.1.16"
    - level-2
    - section-4
    - scored
