---

- name: "1.1.6 - Ensure separate partition exists for /var"
  shell: mount | grep "on /var "
  args:
    warn: false
  register: var_mounted
  tags:
    - level-1
    - section-1
    - "1.1.6"
    - scored
