# Standards: 0.11
---

# 1.4.1 Ensure permissions on bootloader config are configured

- name: 1.4.1 - Set permissions on grub configuration
  file:
    path: "{{ cis_grub_bootloader_filename }}"
    owner: root
    group: root
    mode:  "og-rwx"
    state: file
  tags:
    - level-1
    - "1.4.1"
    - scored
