# Standards: 0.11
---

# 1.7.1.5 Ensure permissions on /etc/issue are configured

- name: 1.7.1.5 - Ensure permissions on /etc/issue are configured
  file:
    path: "/etc/issue"
    owner: ec2-user
    group: ec2-user
    mode: 0644
  tags:
    - level-1
    - 1.7.1.5
    - scored
