# Standards: 0.11
---

# 3.1.1 Ensure IP forwarding is disabled

- name: 3.1.1 - Ensure IP forwarding is disabled
  sysctl:
    name: "{{ item }}"
    value: "0"
    state: present
  with_items:
    - "net.ipv4.ip_forward"
    - "net.ipv6.conf.all.forwarding"
  tags:
    - level-1
    - section-3
    - "3.1.1"
    - scored

- name: 3.1.1 - Ensure IP forwarding is disabled in active kernel parameters
  command: "{{ item }}"
  with_items:
    - "sysctl -w net.ipv4.ip_forward=0"
    - "sysctl -w net.ipv6.conf.all.forwarding=0"
    - "sysctl -w net.ipv4.route.flush=1"
    - "sysctl -w net.ipv6.route.flush=1"
  tags:
    - level-1
    - section-3
    - "3.1.1"
    - scored
