# Standards: 0.11
---

# 3.4.5 Ensure permissions on /etc/hosts.deny are configured

- name: 3.4.5 - Ensure permissions on /etc/hosts.deny are configured
  file:
    path: "/etc/hosts.deny"
    owner: ec2-user
    group: ec2-user
    mode: 0644
  tags:
    - level-1
    - section-3
    - "3.4.5"
    - scored
