# Standards: 0.11
---

# 3.4.4 Ensure permissions on /etc/hosts.allow are configured

- name: 3.4.4 - Ensure permissions on /etc/hosts.allow are configured
  file:
    path: "/etc/hosts.allow"
    owner: ec2-user
    group: ec2-user
    mode: 0644
  tags:
    - level-1
    - section-3
    - "3.4.4"
    - scored
