# Standards: 0.11
---

# 3.4.2 Ensure /etc/hosts.allow is configured

- name: 3.4.2 - Ensure /etc/hosts.allow is configured
  template:
      src: hosts.allow.j2
      dest: /etc/hosts.allow
      owner: root
      group: root
      mode: 0644
  tags:
    - level-1
    - section-3
    - "3.4.2"
    - scored
