# Standards: 0.11
---

# 3.6.2 Ensure default deny firewall policy
- name: "3.6.2 - Ensure firewalld is installed and started"
  yum:
      name: firewalld
      state: present
  notify: restart firewalld
  tags:
    - level-1
    - section-3
    - "3.6.2"
    - scored

- name: "3.6.2 - Ensure firewalld is installed and started"
  service:
      name: firewalld
      state: started
      enabled: yes
  tags:
    - level-1
    - section-3
    - "3.6.2"
    - scored

- name: "3.6.2 - Ensure default deny firewall policy"
  lineinfile:
      path: /etc/firewalld/firewalld.conf
      regexp: "^DefaultZone"
      line: "DefaultZone=drop"
  tags:
    - level-1
    - section-3
    - "3.6.2"
    - scored

- name: "3.6.2 - Ensure default deny firewall policy"
  firewalld:
      state: enabled
      zone: drop
      permanent: true
  tags:
    - level-1
    - section-3
    - "3.6.2"
    - scored
