# Standards: 0.11
---

# 3.6.1 Ensure iptables is installed

- name: 3.6.1 - Ensure iptables is installed
  yum:
    name: "iptables"
    state: latest
  tags:
    - level-1
    - section-3
    - "3.6.1"
    - scored

- name: "3.6.1 - Ensure iptables is started"
  service:
    name: iptables
    state: started
    enabled: yes
  when:
    - firewall == "iptables"
  tags:
    - level-1
    - section-3
    - "3.6.1"
    - scored
