# Standards: 0.11
---

# 5.2.3 - Ensure permissions on SSH public host key files are configured

- name: 5.2.3 - Ensure permissions on SSH private host key files are configured
  command: find /etc/ssh -xdev -type f -name 'ssh_host_*_key.pub' -exec chmod 0644 {} \;
  tags:
    - level-1
    - section-5
    - "5.2.3"
    - scored

- name: 5.2.3 - Ensure permissions on SSH private host key files are configured
  command: find /etc/ssh -xdev -type f -name 'ssh_host_*_key.pub' -exec chown root:root {} \;
  tags:
    - level-1
    - section-5
    - "5.2.3"
    - scored
    
- name: 5.2.3 - Create new dir for authorized_keys dir
  command: mkdir /etc/ssh/ec2-user
  tags:
    - level-1
    - section-5
    - "5.2.3"
    - scored

- name: 5.2.3 - Copy SSH public file to server
  authorized_key: user=ec2-user
                  key="{{ lookup('file', ssh_public_key)}}"
  tags:
    - level-1
    - section-5
    - "5.2.3"
    - scored

- name: 5.2.3 - copy authorized_keys dir from original location to new dir
  command: cp /home/ec2-user/.ssh/authorized_keys /etc/ssh/ec2-user/
  tags:
    - level-1
    - section-5
    - "5.2.3"
    - scored
    
- name: 5.2.3 - Ensure owner of new ssh ec2-user dir is ec2-user
  command: chown -R ec2-user:ec2-user /etc/ssh/ec2-user
  tags:
    - level-1
    - section-5
    - "5.2.3"
    - scored
    
- name: 5.2.3 - Ensure permissions on SSH ec2-user dir are configured
  command: chmod 755 /etc/ssh/ec2-user
  tags:
    - level-1
    - section-5
    - "5.2.3"
    - scored
    
- name: 5.2.3 - Ensure permissions on new SSH authorized_keys dir are configured
  command: chmod 644 /etc/ssh/ec2-user/authorized_keys
  tags:
    - level-1
    - section-5
    - "5.2.3"
    - scored
    
- name: 5.2.3 - Ensure SSH AuthorizedKeysFile is set to new dir
  lineinfile:
    regexp: "^AuthorizedKeysFile\\s+"
    line: "AuthorizedKeysFile /etc/ssh/ec2-user/authorized_keys"
    dest: "{{ cis_sshd_config_filename }}"
  notify: "Restart sshd"
  tags:
    - level-1
    - section-5
    - "5.2.3"
    - scored
