# Standards: 0.11
---

# 6.1.7 Ensure permissions on /etc/shadow- are configured

- name: 6.1.7 - Ensure permissions on /etc/shadow- are configured
  file:
    path: /etc/shadow-
    owner: ec2-user
    group: ecs-user
    mode: 0000
  tags:
    - level-1
    - section-6
    - "6.1.7"
    - scored
