# Standards: 0.11
---

# 6.1.8 Ensure permissions on /etc/group- are configured

- name: 6.1.8 - Ensure permissions on /etc/group- are configured
  file:
    path: /etc/group-
    owner: ec2-user
    group: ec2-user
    mode: 0600
  tags:
    - level-1
    - section-6
    - "6.1.8"
    - scored
